-- phpMyAdmin SQL Dump
-- version 4.6.6deb4+deb9u1
-- https://www.phpmyadmin.net/
--
-- Client :  localhost:3306
-- Généré le :  Lun 17 Janvier 2022 à 09:36
-- Version du serveur :  10.3.31-MariaDB-0+deb10u1
-- Version de PHP :  7.3.31-1~deb10u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `dbjoartzet`
--

-- --------------------------------------------------------

--
-- Structure de la table `news`
--

CREATE TABLE `news` (
  `title` varchar(150) NOT NULL,
  `description` text NOT NULL,
  `link` varchar(150) NOT NULL,
  `guid` varchar(150) NOT NULL,
  `pubDate` varchar(50) NOT NULL,
  `category` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Contenu de la table `news`
--

INSERT INTO `news` (`title`, `description`, `link`, `guid`, `pubDate`, `category`) VALUES
('AMD dévoile un nouveau Ryzen 7 et une nouvelle série de CPUs portables', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/01/olivier-collet-jmwce3w7qkk-unsplash-140x105.jpg\" width=\"140\" height=\"105\" /></noscript><img width=\"2560\" height=\"1920\" src=\"https://www.journaldugeek.com/content/uploads/2021/01/olivier-collet-jmwce3w7qkk-unsplash-scaled.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Le fondeur a annoncé l\'arrivée du Ryzen 7 5800X3D, de la série 6000 pour les portables, mais surtout de la future série 7000 sous Zen 4.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/amd-devoile-un-nouveau-ryzen-7-et-une-nouvelle-serie-de-cpus-portables/\">AMD dévoile un nouveau Ryzen 7 et une nouvelle série de CPUs portables</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/amd-devoile-un-nouveau-ryzen-7-et-une-nouvelle-serie-de-cpus-portables/', 'https://www.journaldugeek.com/?p=50314683', '2022-01-05 18:30:45', 'numerique'),
('Android 12 : Google passe la seconde et annonce les nouveautés à venir en 2022', 'Google prévoyait d\'assister au CES 2022, mais s\'est retiré en raison de préoccupations concernant le COVID-19. Cela n\'aura pas empêché la firme de Mountain View de dévoiler toutes les nouveautés à venir sur Android 12 en 2022. Les voici.', 'https://www.tomsguide.fr/android-12-google-passe-la-seconde-et-annonce-les-nouveautes-a-venir-en-2022/', 'https://www.tomsguide.fr/?p=1106973', '2022-01-06 09:52:57', 'other'),
('Apple travaille bien sur un iPhone pliant, mais il faudra être patient', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/11/iphone-13-apple-1-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/11/iphone-13-apple-1.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"iPhone 13\" /></p>\n<p>L\'iPhone est au coeur de nombreuses rumeurs depuis des années. Dès qu\'un modèle sort, le monde théorise déjà le prochain. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/apple-travaille-bien-sur-un-iphone-pliant-mais-il-faudra-etre-patient/\">Apple travaille bien sur un iPhone pliant, mais il faudra être patient</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/apple-travaille-bien-sur-un-iphone-pliant-mais-il-faudra-etre-patient/', 'https://www.journaldugeek.com/?p=50315426', '2022-01-07 16:30:50', 'other'),
('Apple : un ingénieur de premier plan quitte le navire et passe chez Intel', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/11/template-images-jdg-pptx120-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/11/template-images-jdg-pptx120.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Apple Amazon sur Mac\" /></p>\n<p>Jeff Wilson, grand artisan des phénoménales puces M1, mettra désormais son expertise à la disposition d\'Intel.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/apple-un-ingenieur-de-premier-plan-quitte-le-navire-et-passe-chez-intel/\">Apple&nbsp;: un ingénieur de premier plan quitte le navire et passe chez Intel</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/apple-un-ingenieur-de-premier-plan-quitte-le-navire-et-passe-chez-intel/', 'https://www.journaldugeek.com/?p=50315442', '2022-01-07 17:00:23', 'other'),
('Après Instagram, au tour de Twitter de copier TikTok', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t093212-545-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t093212-545.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Twitter vidéo réaction\" /></p>\n<p>Twitter a annoncé cette semaine le test d\'une nouvelle fonctionnalité sociale, qui n\'est pas sans rappeler ce que propose déjà TikTok. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/apres-instagram-au-tour-de-twitter-de-copier-tiktok/\">Après Instagram, au tour de Twitter de copier TikTok</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/apres-instagram-au-tour-de-twitter-de-copier-tiktok/', 'https://www.journaldugeek.com/?p=50315380', '2022-01-07 17:30:56', 'other'),
('Arc : les premières cartes graphiques dédiées d’Intel arrivent très bientôt', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-11-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-11.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Les constructeurs ont commencé à recevoir les premières cartes Intel Arc; elles pourraient arriver sur le marché dans quelques mois. Suffisant pour bousculer l\'indéboulonnable Nvidia&nbsp;?</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/arc-les-premieres-cartes-graphiques-dediees-dintel-arrivent-tres-bientot/\">Arc&nbsp;: les premières cartes graphiques dédiées d&#8217;Intel arrivent très bientôt</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/arc-les-premieres-cartes-graphiques-dediees-dintel-arrivent-tres-bientot/', 'https://www.journaldugeek.com/?p=50314714', '2022-01-06 10:11:06', 'numerique'),
('Asus dévoile un Zenbook doté d’un écran 17 pouces OLED pliable', 'Depuis plusieurs années, les écrans OLED pliables tentent de s&#8217;imposer sur les smartphones. L&#8217;année 2022 sera peut être celle où on verra se développer ce concept sur les PC portables. Car si &#8211; pour l&#8217;instant &#8211; seul Lenovo propose un PC portable doté d&#8217;un écran OLED pliable de 13,3 pouces, le ThinkPad X1 Fold, Samsung [&#8230;]', 'https://www.tomsguide.fr/asus-devoile-un-zenbook-dote-dun-ecran-17-pouces-oled-pliable/', 'https://www.tomsguide.fr/?p=1106720', '2022-01-05 17:45:00', 'numerique'),
('Asus Zenbook 14 OLED et Space Edition : des ordinateurs de l’espace', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/space-edition-zenbook-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/space-edition-zenbook.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"space-edition-zenbook\" /></p>\n<p>Asus a décidé de faire de grandes annonces à cette édition du CES 2022. Après avoir surpris avec le Zenbook Fold, voilà la \"Space Edition\". </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/asus-zenbook-14-oled-et-space-edition-des-ordinateurs-de-lespace/\">Asus Zenbook 14 OLED et Space Edition&nbsp;: des ordinateurs de l&#8217;espace</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/asus-zenbook-14-oled-et-space-edition-des-ordinateurs-de-lespace/', 'https://www.journaldugeek.com/?p=50314487', '2022-01-05 18:00:18', 'numerique'),
('Asus Zenbook Fold 17 OLED : les ordinateurs aussi peuvent être pliants', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/asus-zenbook-fold-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/asus-zenbook-fold.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"asus-zenbook-fold\" /></p>\n<p>Asus est une marque innovante dans le monde de l\'informatique. Avec le Zenbook Fold, la firme propose un produit encore jamais vu. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/asus-zenbook-fold-17-oled-les-ordinateurs-aussi-peuvent-etre-pliants/\">Asus Zenbook Fold 17 OLED&nbsp;: les ordinateurs aussi peuvent être pliants</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/asus-zenbook-fold-17-oled-les-ordinateurs-aussi-peuvent-etre-pliants/', 'https://www.journaldugeek.com/?p=50314492', '2022-01-05 17:45:46', 'numerique'),
('CES 2022: Lili, la lampe qui aide les personnes dyslexiques', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre127-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre127.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"lili lampe dyslexie\" /></p>\n<p>Lors du CES 2022 l’entreprise Lili For Life a annoncé que sa lampe à destination des dyslexiques serait bientôt disponible à travers le monde. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-lili-la-lampe-qui-aide-les-personnes-dyslexiques/\">CES 2022: Lili, la lampe qui aide les personnes dyslexiques</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-lili-la-lampe-qui-aide-les-personnes-dyslexiques/', 'https://www.journaldugeek.com/?p=50314864', '2022-01-06 08:30:14', 'other'),
('CES 2022 : Acer présente de nouveaux portables Predator pour les gamers de l’extrême', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/predator-helios-300-ph317-56-05-140x105.jpg\" width=\"140\" height=\"105\" /></noscript><img width=\"1000\" height=\"750\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/predator-helios-300-ph317-56-05.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Nvidia et Intel viennent d\'annoncer leurs nouveautés, et Acer compte bien les utiliser pour partir à la chasse aux benchmarks avec des Predator à la puissance monstrueuse.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-acer-presente-de-nouveaux-portables-predator-pour-les-gamers-de-lextreme/\">CES 2022&nbsp;: Acer présente de nouveaux portables Predator pour les gamers de l&#8217;extrême</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-acer-presente-de-nouveaux-portables-predator-pour-les-gamers-de-lextreme/', 'https://www.journaldugeek.com/?p=50315032', '2022-01-06 10:00:24', 'numerique'),
('CES 2022 : AfterShokz change de nom, et présente un nouveau casque à conduction osseuse', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t121453-641-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t121453-641.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Shokz OpenRun produit\" /></p>\n<p>Le spécialiste de la conduction osseuse AfterShokz devient Shokz, et profite du CES 2022 pour présenter un nouveau modèle. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/ces-2022-aftershokz-change-de-nom-et-presente-un-nouveau-casque-a-conduction-osseuse/\">CES 2022&nbsp;: AfterShokz change de nom, et présente un nouveau casque à conduction osseuse</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/ces-2022-aftershokz-change-de-nom-et-presente-un-nouveau-casque-a-conduction-osseuse/', 'https://www.journaldugeek.com/?p=50314627', '2022-01-05 19:30:44', 'numerique'),
('CES 2022 : Anker présente une webcam pour avoir meilleure mine', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre128-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre128.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"anker webcam glowup\" /></p>\n<p>À l’occasion du CES 2022, Anker dévoile sa nouvelle webcam 2K qui promet de vous montrer sous votre meilleur jour, mais c\'est cher. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-anker-presente-une-webcam-pour-avoir-meilleure-mine/\">CES 2022&nbsp;: Anker présente une webcam pour avoir meilleure mine</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-anker-presente-une-webcam-pour-avoir-meilleure-mine/', 'https://www.journaldugeek.com/?p=50314962', '2022-01-06 09:00:30', 'numerique'),
('CES 2022 : JBL dévoile une foule de nouveaux produits pour le printemps', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre124-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre124.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"JBL CES 2022\" /></p>\n<p>JBL profite de CES pour présenter de nombreux nouveaux produits, à l\'usage des mélomanes, des fêtards et des gamers. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/ces-2022-jbl-devoile-une-foule-de-nouveaux-produits-pour-le-printemps/\">CES 2022&nbsp;: JBL dévoile une foule de nouveaux produits pour le printemps</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/ces-2022-jbl-devoile-une-foule-de-nouveaux-produits-pour-le-printemps/', 'https://www.journaldugeek.com/?p=50314580', '2022-01-05 17:00:49', 'numerique'),
('CES 2022 : Lenovo présente ses nouveaux pc portables ThinkPad', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/fgh-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/fgh.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>La célèbre gamme d\'ordinateurs portable aura désormais droit aux tout nouveaux Ryzen PRO 6000, pour des niveaux de performances et de sécurité jamais vus sur ces appareils.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-lenovo-presente-ses-nouveaux-pc-portables-thinkpad/\">CES 2022&nbsp;: Lenovo présente ses nouveaux pc portables ThinkPad</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-lenovo-presente-ses-nouveaux-pc-portables-thinkpad/', 'https://www.journaldugeek.com/?p=50314838', '2022-01-06 08:00:44', 'numerique'),
('CES 2022 : MSI conclut son CES en beauté avec une pluie de hardware', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-21-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-21.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>MSI conclut son CES avec le dernier-né de la gamme Aegis, mais aussi du nouveau hardware dont des cartes mères, GPUS et périphériques.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/ces-2022-msi-conclut-son-ces-en-beaute-avec-une-pluie-de-hardware/\">CES 2022&nbsp;: MSI conclut son CES en beauté avec une pluie de hardware</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/ces-2022-msi-conclut-son-ces-en-beaute-avec-une-pluie-de-hardware/', 'https://www.journaldugeek.com/?p=50315526', '2022-01-07 17:45:03', 'numerique'),
('CES 2022 : quand la technologie autonome envahit les champs', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t170633-134-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t170633-134.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"tracteur autonome ces 2022\" /></p>\n<p>L’automatisation des outils de travail agricoles atteint un niveau inespéré avec ce tracteur autonome présenté au CES 2022. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-quand-la-technologie-autonome-envahit-les-champs/\">CES 2022&nbsp;: quand la technologie autonome envahit les champs</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-quand-la-technologie-autonome-envahit-les-champs/', 'https://www.journaldugeek.com/?p=50314965', '2022-01-06 09:15:32', 'other'),
('CES 2022 : souris, claviers, casques… HyperX annonce du lourd', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t140700-216-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t140700-216.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"accessoires gamings hyperx CES 2022\" /></p>\n<p>Pour ce CES 2022, HyperX a présenté une panoplie d’accessoires. On fait le point sur toutes les annonces de la marque. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/ces-2022-souris-claviers-casques-hyperx-annonce-du-lourd/\">CES 2022&nbsp;: souris, claviers, casques… HyperX annonce du lourd</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/ces-2022-souris-claviers-casques-hyperx-annonce-du-lourd/', 'https://www.journaldugeek.com/?p=50314764', '2022-01-05 20:00:58', 'numerique'),
('CES 2022 : TCL nous en met plein la vue avec ses NXTWEAR AIR', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre117-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre117.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"TCL lunettes AIR\" /></p>\n<p>Seulement quelques mois après avoir présenté ces NXTWEAR G, TCL revient avec la version allégée de ces lunettes à écran portables, pour plus de confort et toujours une expérience grand écran à portée de main.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-tcl-nous-en-met-plein-la-vue-avec-ses-nxtwear-air/\">CES 2022&nbsp;: TCL nous en met plein la vue avec ses NXTWEAR AIR</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-tcl-nous-en-met-plein-la-vue-avec-ses-nxtwear-air/', 'https://www.journaldugeek.com/?p=50314481', '2022-01-06 10:30:47', 'numerique'),
('CES 2022 : Une start-up française présente son potager d’intérieur connecté', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t162100-934-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t162100-934.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Multo de Prêt à pousser, potager connecté\" /></p>\n<p>Présente au CES 2022, la start-up française Prêt à Pousser vient de présenter son premier potager d’intérieur XXL, et vise désormais une expansion à l’international.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/ces-2022-une-start-up-francaise-presente-son-potager-dinterieur-connecte/\">CES 2022&nbsp;: Une start-up française présente son potager d’intérieur connecté</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/ces-2022-une-start-up-francaise-presente-son-potager-dinterieur-connecte/', 'https://www.journaldugeek.com/?p=50314884', '2022-01-06 09:30:21', 'Ville du Futur'),
('Découvrez les 3 meilleurs offres VPN de ce début d’année', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/top-bons-plans-vpn-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/top-bons-plans-vpn.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Top bons plans VPN\" /></p>\n<p>Parce que la sécurité n’attend pas, découvrez les meilleures offres VPN de ce début d’année 2022, chez 3 grands logiciels.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/decouvrez-les-3-meilleurs-offres-vpn-de-ce-debut-dannee/\">Découvrez les 3 meilleurs offres VPN de ce début d’année</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/decouvrez-les-3-meilleurs-offres-vpn-de-ce-debut-dannee/', 'https://www.journaldugeek.com/?p=50314164', '2022-01-05 20:00:55', 'promo'),
('Fitbit fait son bilan de l’année 2021, et pointe une fatigue généralisée', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/12/template-jdg-2021-12-10t102002-059-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/12/template-jdg-2021-12-10t102002-059.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"fitbit charge 5 smartband test\" /></p>\n<p>Fort de ses produits connectés dédiés à la santé et au suivi d\'activité, Fitbit a présenté hier son bilan de l\'année 2021. Sans grande surprise, c\'est la fatigue qui prédomine. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/fitbit-fait-son-bilan-de-lannee-2021-et-pointe-une-fatigue-generalisee/\">Fitbit fait son bilan de l&#8217;année 2021, et pointe une fatigue généralisée</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/fitbit-fait-son-bilan-de-lannee-2021-et-pointe-une-fatigue-generalisee/', 'https://www.journaldugeek.com/?p=50315068', '2022-01-06 11:00:39', 'other'),
('Google Maps permet à la police d’arrêter un mafieux italien en cavale depuis 20 ans', 'Google Maps est un outil très utile pour se repérer mais aussi pour enquêter sur des criminels en cavale. Tout récemment, un ponte de la mafia italienne a notamment été arrêté grâce à l\'application. ', 'https://www.tomsguide.fr/google-maps-permet-a-la-police-darreter-un-mafieux-italien-en-cavale-depuis-20-ans/', 'https://www.tomsguide.fr/?p=1107312', '2022-01-07 14:41:06', 'other'),
('Google veut transformer votre smartphone en clé pour BMW', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/08/google-pixel-5a-main-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/08/google-pixel-5a-main.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Google Pixel 5a\" /></p>\n<p>Malgré son absence au CES 2022, Google annonce une série de nouvelles fonctionnalités pour ses produits. Les smartphones Samsung et Pixel vont devenir des clés de voiture.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/google-veut-transformer-votre-smartphone-en-cle-pour-bmw/\">Google veut transformer votre smartphone en clé pour BMW</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/google-veut-transformer-votre-smartphone-en-cle-pour-bmw/', 'https://www.journaldugeek.com/?p=50314712', '2022-01-05 19:01:59', 'digitalNews'),
('Grosse baisse du prix pour l’excellent Xiaomi Mi 11 Lite 5G', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/09/xiaomi-11-lite-5g-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/09/xiaomi-11-lite-5g.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Aliexpress propose le Xiaomi Mi 11 Lite 5G à un prix très bas à l\'occasion d\'un deal exclusif pour ce début d\'année&nbsp;!</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/bon-plan/grosse-baisse-du-prix-pour-lexcellent-xiaomi-mi-11-lite-5g/\">Grosse baisse du prix pour l&#8217;excellent Xiaomi Mi 11 Lite 5G</a></p>\n', 'https://www.journaldugeek.com/bon-plan/grosse-baisse-du-prix-pour-lexcellent-xiaomi-mi-11-lite-5g/', 'https://www.journaldugeek.com/?post_type=bonplan&p=50315118', '2022-01-06 10:53:12', 'promo'),
('Harry Potter renforce l’antisémitisme selon un commentateur politique', 'Selon Jon Stewart, Harry Potter véhicule un message antisémite. Le commentateur politique reproche l\'aspect des gobelins qui dirigent la banque souterraine. Le physique de ces personnages renvoient à de vieilles caricatures des Protocoles Des Sages de Sion.', 'https://www.tomsguide.fr/harry-potter-renforce-lantisemitisme-selon-un-commentateur-politique/', 'https://www.tomsguide.fr/?p=1106859', '2022-01-05 17:13:46', 'cineSerieManga'),
('Il transforme sa GameCube en Dock pour Nintendo Switch 100 % fonctionnel', 'Reddit contient parfois de véritables petites pépites. Un utilisateur dévoile aujourd\'hui il a réussi à savamment faire du neuf avec du vieux en transformant une GameCube en Dock pour sa Nintendo Switch. L\'ensemble fonctionne à merveille.', 'https://www.tomsguide.fr/il-transforme-sa-gamecube-en-dock-pour-nintendo-switch-100-fonctionnel/', 'https://www.tomsguide.fr/?p=1106986', '2022-01-06 10:27:49', 'other'),
('Instagram : les nouvelles publications pourront bientôt s’afficher de trois manières différentes', 'Sur Instagram, le fil de publications était chapeauté jusqu\'alors par des algorithmes. Mais le patron du réseau social vient de révéler que l\'affichage chronologique allait faire son grand retour. Deux autres options d\'affichage seront également disponibles. On fait le point. ', 'https://www.tomsguide.fr/instagram-les-nouvelles-publications-pourront-bientot-safficher-de-trois-manieres-differentes/', 'https://www.tomsguide.fr/?p=1106972', '2022-01-06 09:44:05', 'other'),
('iPhone : comment espionner des conversations avec vos Airpods ?', 'Apple a déployé sa technologie d\'écoute en temps réel (Apple Live Listen). Elle permet à votre iPhone (ou autre appareil iOS) d\'agir comme un microphone qui renvoie le son vers vos AirPods.', 'https://www.tomsguide.fr/votre-iphone-peut-secretement-ecouter-des-conversations-grace-aux-airpods-voici-comment/', 'https://www.tomsguide.fr/?p=1107314', '2022-01-07 14:57:48', 'other'),
('Le combo clavier et souris Logitech MK235 est à 17,49 € seulement', 'Chez Amazon, le clavier Logitech MK235 est à 17,49 € au lieu de 29,99 €.', 'https://www.tomsguide.fr/le-combo-clavier-et-souris-logitech-mk235-est-a-1749-e-seulement/', 'https://www.tomsguide.fr/?p=1106777', '2022-01-07 17:28:49', 'other'),
('Le grand amour de Luke Skywalker révélé par la nouvelle série Star Wars', 'Le nouvel épisode de The Book of Boba Fett présente le grand amour de Luke Skywalker dans une scène passée inaperçue.', 'https://www.tomsguide.fr/le-grand-amour-de-luke-skywalker-revele-par-la-nouvelle-serie-star-wars/', 'https://www.tomsguide.fr/?p=1107381', '2022-01-07 18:11:58', 'other'),
('Le Japon va développer un canon électromagnétique pour intercepter des missiles', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-18-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-18.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Le gouvernement nippon veut se doter d\'un railgun capable de pulvériser des missiles hypersoniques en plein vol.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/le-japon-va-developper-un-canon-electromagnetique-pour-intercepter-des-missiles/\">Le Japon va développer un canon électromagnétique pour intercepter des missiles</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/le-japon-va-developper-un-canon-electromagnetique-pour-intercepter-des-missiles/', 'https://www.journaldugeek.com/?p=50315469', '2022-01-07 18:00:43', 'other'),
('Le Livre de Boba Fett vs The Mandalorian : Robert Rodriguez détaille les différences entre les deux séries', 'Le Livre de Boba Fett est un spin-off de The Mandalorian. D\'où le fait que les deux programmes aient des similitudes. Mais ils se distinguent évidemment sur plusieurs aspects, comme le détaille Robert Rodriguez, le réalisateur du premier épisode de la nouvelle série Disney+.', 'https://www.tomsguide.fr/le-livre-de-boba-fett-vs-the-mandalorian-robert-rodriguez-detaille-les-differences-entre-les-deux-series/', 'https://www.tomsguide.fr/?p=1106987', '2022-01-06 10:55:17', 'other'),
('Le smartphone Xiaomi Redmi Note 10 Pro est à 269,53 € chez Amazon', 'Chez Amazon, le smartphone Xiaomi Redmi Note 10 Pro est à 269,53 € au lieu de 329,90 €. ', 'https://www.tomsguide.fr/le-smartphone-xiaomi-redmi-note-10-pro-est-a-26953-e-chez-amazon/', 'https://www.tomsguide.fr/?p=1107387', '2022-01-07 18:02:36', 'other'),
('Lenovo présente le ThinkBook Plus Gen 3, un superbe double-écran plutôt abordable', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-16-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-16.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Les portables à deux écrans vous parlent, mais les ZenBooks sont trop chers ou pas adaptés&nbsp;? Lenovo compte bien y remédier.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/lenovo-presente-le-thinkbook-plus-gen-3-un-superbe-double-ecran-plutot-abordable/\">Lenovo présente le ThinkBook Plus Gen 3, un superbe double-écran plutôt abordable</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/lenovo-presente-le-thinkbook-plus-gen-3-un-superbe-double-ecran-plutot-abordable/', 'https://www.journaldugeek.com/?p=50315417', '2022-01-07 16:45:28', 'numerique'),
('Les écouteurs OnePlus Buds Pro disponibles à leur plus bas prix !', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/onepluspro-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/onepluspro.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>C\'est sur Amazon qu\'on trouve aujourd\'hui les derniers écouteurs OnePlus Buds Pro à prix réduit, du jamais vu sur ce produit pour le moment&nbsp;!</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/bon-plan/les-ecouteurs-oneplus-buds-pro-disponibles-a-leur-plus-bas-prix/\">Les écouteurs OnePlus Buds Pro disponibles à leur plus bas prix&nbsp;!</a></p>\n', 'https://www.journaldugeek.com/bon-plan/les-ecouteurs-oneplus-buds-pro-disponibles-a-leur-plus-bas-prix/', 'https://www.journaldugeek.com/?post_type=bonplan&p=50315089', '2022-01-06 10:15:21', 'numerique'),
('NASA : l’assistant vocal Alexa équipera le vaisseau spatial Orion', 'Le vaisseau spatial Orion de la NASA, dont le lancement est prévu début 2022 dans le cadre de la mission lunaire Artemis I, décollera avec l\'assistant vocal d\'Amazon Alexa à son bord.', 'https://www.tomsguide.fr/nasa-lassistant-vocal-alexa-equipera-le-vaisseau-spatial-orion/', 'https://www.tomsguide.fr/?p=1106821', '2022-01-05 15:19:34', 'professional'),
('Netflix va vous faire frissonner avec Archive 81', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre129-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre129.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"netflix archive 81\" /></p>\n<p>La plateforme vient de partager la bande-annonce d’Archive 81, à mi-chemin entre Paranormal Activity et Last Night in Soho.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/netflix-va-vous-faire-frissonner-avec-archive-81/\">Netflix va vous faire frissonner avec Archive 81</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/netflix-va-vous-faire-frissonner-avec-archive-81/', 'https://www.journaldugeek.com/?p=50315070', '2022-01-06 12:00:20', 'other'),
('Nintendo Switch : un Mario Kart exclusif en préparation ?', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t125848-092-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t125848-092.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"mario kart 10 leak nintendo switch\" /></p>\n<p>Un leaker laisse à croire que Nintendo serait en train de travailler sur Mario Kart 10, le premier opus de la franchise exclusif à la Nintendo Switch. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/nintendo-switch-un-mario-kart-exclusif-en-preparation/\">Nintendo Switch&nbsp;: un Mario Kart exclusif en préparation&nbsp;?</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/nintendo-switch-un-mario-kart-exclusif-en-preparation/', 'https://www.journaldugeek.com/?p=50315465', '2022-01-07 19:00:09', 'videoGames'),
('Oculus Quest 3 et Quest Pro : uOLED, mini LED, date de sortie, une fuite dévoile de grosses améliorations', 'L’Oculus Quest 3 et Quest Pro qui seront respectivement appelés Meta Quest 3 et Meta Cambria promettent de grosses améliorations. Une fuite a révélé les caractéristiques des casques de réalité virtuelle ainsi que leur date de sortie et d’autres infos.', 'https://www.tomsguide.fr/oculus-quest-3-et-quest-pro-uoled-mini-led-date-de-sortie-une-fuite-devoile-de-grosses-ameliorations/', 'https://www.tomsguide.fr/?p=1106966', '2022-01-06 05:01:38', 'other'),
('Oculus Quest 3 et Quest Pro : un leak dévoile fiche technique et date de sortie', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2021/10/template-jdg-53-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2021/10/template-jdg-53.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Facebook Oculus casque VR\" /></p>\n<p>Sans doute renommés Meta Quest 3 et Meta Cambria au moment de leur sortie, les Oculus Quest 3 et Quest Pro ont eu droit à un important leak cette semaine. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/oculus-quest-3-et-quest-pro-un-leak-devoile-fiche-technique-et-date-de-sortie/\">Oculus Quest 3 et Quest Pro&nbsp;: un leak dévoile fiche technique et date de sortie</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/oculus-quest-3-et-quest-pro-un-leak-devoile-fiche-technique-et-date-de-sortie/', 'https://www.journaldugeek.com/?p=50315415', '2022-01-07 18:30:40', 'other'),
('On vous offre un Oppo Find X3 Lite, le smartphone équilibré qu’il vous faut', 'Pour débuter 2022, on vous offre un Oppo Find X3 Lite. Un smartphone équilibré, puissant, beau, bref un excellent compagnon pour affronter la nouvelle année.', 'https://www.tomsguide.fr/gagnez-un-oppo-find-x3-lite-le-smartphone-equilibre-quil-vous-faut/', 'https://www.tomsguide.fr/?p=1106872', '2022-01-05 17:22:22', 'jeux-concours'),
('OnePlus 10 Pro : l’appareil photo est-il son vrai point fort ?', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-04t101107-693-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-04t101107-693.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Oneplus 10 pro teaser\" /></p>\n<p>OnePlus a surpris en présentant le OnePlus 10 Pro au CES 2022, depuis on en apprend tous les jours un peu plus sur ce téléphone.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/oneplus-10-pro-lappareil-photo-est-il-son-vrai-point-fort/\">OnePlus 10 Pro&nbsp;: l&#8217;appareil photo est-il son vrai point fort&nbsp;?</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/oneplus-10-pro-lappareil-photo-est-il-son-vrai-point-fort/', 'https://www.journaldugeek.com/?p=50315472', '2022-01-07 18:30:33', 'other'),
('Pénurie de PS5 ? Comme lui, montez la vôtre en LEGO !', 'BrickinNick est un builder très créatif qui adore les Legos. Sur son compte Twitter, il nous montre sa toute dernière réussite : une PS5 et une Xbox Series X, toutes deux à l\'échelle 1: 1, qui pourraient bien être commercialisées un jour si elles récoltent suffisamment de soutien via LEGO Ideas.', 'https://www.tomsguide.fr/lego-il-construit-la-ps5-la-xbox-series-x-et-leurs-manettes-a-taille-reelle/', 'https://www.tomsguide.fr/?p=1107335', '2022-01-07 15:54:18', 'other'),
('PopCorn Time : le “Netflix des pirates” ferme définitivement ses portes', 'PopCorn Time permettait à bon nombre d\'internautes de visionner gratuitement films et séries, en toute illégalité. Mais la plateforme a finalement fermé ses portes, alors que la pression de l\'industrie du septième art et des plateformes de SVOD s\'amplifiait sensiblement. ', 'https://www.tomsguide.fr/popcorn-time-le-netflix-des-pirates-ferme-definitivement-ses-portes/', 'https://www.tomsguide.fr/?p=1106902', '2022-01-05 18:36:08', 'digitalNews'),
('Pour les soldes, Cdiscount propose une carte cadeau de 150€ au prix de 130€', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/cartecd-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/cartecd.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"\" /></p>\n<p>Cdiscount propose actuellement une carte cadeau de 150€ au prix de 130€ qui sera valable pour les soldes le 12 janvier prochain&nbsp;!</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/?post_type=bonplan&#038;p=50315124\">Pour les soldes, Cdiscount propose une carte cadeau de 150€ au prix de 130€</a></p>\n', 'https://www.journaldugeek.com/?post_type=bonplan&p=50315124', 'https://www.journaldugeek.com/?post_type=bonplan&p=50315124', '2022-01-06 11:45:06', 'promo'),
('PS Plus : certains joueurs ont une mauvaise surprise avec les jeux offerts de janvier sur PS4 et PS5', 'Les abonnés PS Plus peuvent récupérer gratuitement trois jeux offerts pour le mois de janvier 2022 sur PS4 et PS5. Néanmoins, certains joueurs ont eu une mauvaise surprise en ce qui concerne les jeux offerts.', 'https://www.tomsguide.fr/ps-plus-certains-joueurs-ont-une-mauvaise-surprise-avec-les-jeux-offerts-de-janvier-sur-ps4-et-ps5/', 'https://www.tomsguide.fr/?p=1106961', '2022-01-06 04:00:17', 'Jeux vidéo'),
('PSVR 2 PS5 : OLED, 4K HDR, 120 Hz, Sony présente son casque VR en détail', 'Sony a enfin évoqué les caractéristiques de son nouveau casque de VR pour PS5. Très attendu par les joueurs, son nom et quelques-unes de ses caractéristiques principales ont été confirmées, mais pas que. Un jeu exclusif au PSVR 2, tiré d\'une IP appréciée, a également été présenté.', 'https://www.tomsguide.fr/psvr-2-ps5-oled-4k-hdr-120-hz-sony-presente-son-casque-vr-en-detail/', 'https://www.tomsguide.fr/?p=1106698', '2022-01-05 18:28:00', 'numerique'),
('Samsung présente Odyssey Ark, son plus grand écran incurvé', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t155850-699-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t155850-699.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"samsung odyssey ark ces 2022\" /></p>\n<p>Le CES 2022 a été l’occasion pour Samsung de faire une démonstration de force avec son plus grand écran incurvé, Odyssey Ark. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/samsung-presente-odyssey-ark-son-plus-grand-ecran-incurve/\">Samsung présente Odyssey Ark, son plus grand écran incurvé</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/samsung-presente-odyssey-ark-son-plus-grand-ecran-incurve/', 'https://www.journaldugeek.com/?p=50314871', '2022-01-05 17:45:04', 'numerique'),
('Sony lance des téléviseurs QD-OLED et Mini-LED exceptionnels', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sony-tv-oled-mini-led-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sony-tv-oled-mini-led.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"sony-tv-oled-mini-led\" /></p>\n<p>Sony vient de faire de nombreuses annonces pour lancer 2022. Parmi les projets de la marque, les télévisions ont toujours une place de choix. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/sony-lance-des-televiseurs-qd-oled-et-mini-led-exceptionnels/\">Sony lance des téléviseurs QD-OLED et Mini-LED exceptionnels</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/sony-lance-des-televiseurs-qd-oled-et-mini-led-exceptionnels/', 'https://www.journaldugeek.com/?p=50314755', '2022-01-06 12:15:24', 'numerique'),
('Star Wars KOTOR : le remake s’inspirerait des combats de God of War et Nioh', 'Si sa date de sortie reste à ce jour inconnue, Star Wars: Knights of the Old Republic Remake est bel et bien dans les cartons d\'Aspyr et de Lucasfilm Games. Aujourd\'hui, de nouvelles rumeurs évoquent son éventuel gameplay, qui se rapprocherait de God of War, sorti en 2018, ainsi que de Nioh, en 2017.', 'https://www.tomsguide.fr/star-wars-kotor-le-remake-sinspirerait-des-combats-de-god-of-war-et-nioh/', 'https://www.tomsguide.fr/?p=1107383', '2022-01-07 18:09:10', 'other'),
('Steam Awards : quels sont les meilleurs jeux PC de 2021 ?', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t113435-376-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-07t113435-376.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"cyberpunk 2077 steam awards\" /></p>\n<p>Valve présente son classement des meilleurs jeux PC (Steam) grâce à son système de récompenses Steam Awards. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/07/steam-awards-quels-sont-les-meilleurs-jeux-pc-de-2021/\">Steam Awards&nbsp;: quels sont les meilleurs jeux PC de 2021&nbsp;?</a></p>\n', 'https://www.journaldugeek.com/2022/01/07/steam-awards-quels-sont-les-meilleurs-jeux-pc-de-2021/', 'https://www.journaldugeek.com/?p=50315432', '2022-01-07 16:00:31', 'videoGames'),
('Sundance : l’organisation mise finalement sur un festival virtuel', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre130-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/sans-titre130.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"sundance affiche\" /></p>\n<p>Face à la recrudescence du COVID-19, Sundance annule son événement en personne et mise désormais sur une édition 2022 100&nbsp;% en ligne, comme l’année précédente.</p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/06/sundance-lorganisation-mise-finalement-sur-un-festival-virtuel/\">Sundance&nbsp;: l’organisation mise finalement sur un festival virtuel</a></p>\n', 'https://www.journaldugeek.com/2022/01/06/sundance-lorganisation-mise-finalement-sur-un-festival-virtuel/', 'https://www.journaldugeek.com/?p=50315086', '2022-01-06 11:30:23', 'cineSerieManga'),
('Sur TikTok, une star de télé-réalité vend ses pets en NFT', '<p><noscript><img src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t152404-934-158x105.jpg\" width=\"158\" height=\"105\" /></noscript><img width=\"1400\" height=\"932\" src=\"https://www.journaldugeek.com/content/uploads/2022/01/template-jdg-2022-01-05t152404-934.jpg\" class=\"attachment-full size-full wp-post-image\" alt=\"Fart Jar NFT\" /></p>\n<p>Vendre des pets virtuels en NFT, une tendance qui a le vent en poupe sur les réseaux sociaux. </p>\n<p><a rel=\"nofollow\" href=\"https://www.journaldugeek.com/2022/01/05/sur-tiktok-une-star-de-tele-realite-vend-ses-pets-en-nft/\">Sur TikTok, une star de télé-réalité vend ses pets en NFT</a></p>\n', 'https://www.journaldugeek.com/2022/01/05/sur-tiktok-une-star-de-tele-realite-vend-ses-pets-en-nft/', 'https://www.journaldugeek.com/?p=50314808', '2022-01-05 17:15:49', 'socialMedia'),
('The Batman : nouvel extrait avec Catwoman et le Pingouin', 'Petite surprise pour les fans du justicier. The Batman dévoile un nouvel extrait de 30 secondes !', 'https://www.tomsguide.fr/the-batman-nouvel-extrait-avec-catwoman-et-le-pingouin/', 'https://www.tomsguide.fr/?p=1106927', '2022-01-05 20:17:51', 'cineSerieManga'),
('The Boys saison 3 : on connaît enfin sa date de sortie !', 'Diffusée sur Amazon Prime Video, la série The Boys a réussi a trouver son public grâce à son côté trash et son intrigue détonnant avec les contenus superhéroïques habituels. Bonne nouvelle, la date de sortie de la saison 3 a été officiellement annoncée. ', 'https://www.tomsguide.fr/the-boys-saison-3-on-connait-enfin-sa-date-de-sortie/', 'https://www.tomsguide.fr/?p=1107384', '2022-01-07 18:26:47', 'other'),
('The Flash : Ben Affleck enfilera le costume de Batman pour la dernière fois', 'Après avoir incarné pendant longtemps Batman dans le DCEU, Ben Affleck s\'apprête à tirer sa révérence. En guise de baroud d\'honneur, il sera à l\'affiche de The Flash au coté d\'Ezra Miller. ', 'https://www.tomsguide.fr/the-flash-ben-affleck-enfilera-le-costume-de-batman-pour-la-derniere-fois/', 'https://www.tomsguide.fr/?p=1107336', '2022-01-07 16:15:49', 'cineSerieManga'),
('Tim Cook a gagné 1447 fois plus d’argent que l’employé moyen d’Apple en 2021', 'Alors que les ventes de produits Apple sont toujours au beau fixe, Tim Cook a décroché le jackpot en 2021. Une rémunération bien supérieure à celles qu\'il avait touchées les précédentes années. ', 'https://www.tomsguide.fr/tim-cook-a-gagne-1447-fois-plus-dargent-que-lemploye-moyen-dapple-en-2021/', 'https://www.tomsguide.fr/?p=1107302', '2022-01-07 12:53:38', 'other'),
('Ubisoft+ : le service d’abonnement pour jouer en illimité arrive sur les consoles Xbox', 'Ubisoft vient d’annoncer l’arrivée de son service d’abonnement, Ubisoft+, sur les consoles Xbox, à savoir la Xbox One et les Xbox Series X/S. Celui-ci permet de jouer en illimité à la bibliothèque des jeux Ubisoft pour 14,99 € par mois.', 'https://www.tomsguide.fr/ubisoft-le-service-dabonnement-pour-jouer-en-illimite-arrive-sur-les-consoles-xbox/', 'https://www.tomsguide.fr/?p=1106952', '2022-01-06 02:49:59', 'Jeux vidéo'),
('Voici la Razer x Fossil Gen 6, une smartwatch calibrée pour les gamers', 'Lors du CES 2022, Razer a dévoilé le fruit de sa collaboration avec Fossil : la Razer X Fossil Gen 6 Smartwatch. Une montre en édition limitée qui fait les yeux doux aux gamers. Prix, date de sortie, caractéristiques, voici ce qu\'il faut savoir. ', 'https://www.tomsguide.fr/voici-la-razer-x-fossil-gen-6-une-smartwatch-calibree-pour-les-gamers/', 'https://www.tomsguide.fr/?p=1106923', '2022-01-05 20:00:11', 'numerique');

-- --------------------------------------------------------

--
-- Structure de la table `User`
--

CREATE TABLE `User` (
  `login` varchar(50) NOT NULL,
  `mdp` varchar(100) NOT NULL,
  `role` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Contenu de la table `User`
--

INSERT INTO `User` (`login`, `mdp`, `role`) VALUES
('', '', 0),
('jubloux', 'Azerty1234', 1),
('superadmin', '$2y$10$GCYlJ83Vt9mswreUm5Nfi.W.QTjZAVRqGgLaa9rAwCaNBDR2PvM4q', 2),
('joartzet', '$2y$10$EH1Rlqv3WEXRcsuoQY1bLeU71M9gT0I/20NDtsSi9oL.R7fd4TP9O', 1),
('tototo', '$2y$10$r2U3LspoeZ5//f2yIQ1UUuKamiUfh0ybG.Tq5L60.Mxq0wzp58cd.', 0);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`title`),
  ADD UNIQUE KEY `uniq_link` (`link`),
  ADD UNIQUE KEY `uniq_guid` (`guid`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
